name: 🐞 Bug Report
description: Something isn't working, broken, not expected behavior
labels: [ bug ]
body:
  - type: markdown
    attributes:
      value: |
        This ticket is about bugs, so broken, not expected behavior. Feedback about this form is appreciated.
  - type: textarea
    attributes:
      label: What happened?
      description: What behavior is observed?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What did you expect?
      description: What behavior is expected?
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: The actions that cause the issues. Please explain it in detail.
  - type: input
    attributes:
      label: Plugin list
      description: This can be found by running `/pl`
      placeholder: AuthMe, ProtocolLib, ...
  - type: input
    attributes:
      label: Configuration file
      description: |
        Link to the contents of your config.yml file.
        You can use [GitHub](https://gist.github.com/), [Hastebin](https://hastebin.com) or similar for that.
      placeholder: https://gist.github.com/games647/88c4439e1cd7810f21318b1b24a04ee0
  - type: textarea
    attributes:
      label: Server log
      description: The error, stacktrace or link the complete log. You can use the links above for long versions.
      placeholder: https://hastebin.com/ / https://gist.github.com/
  - type: input
    attributes:
      label: Plugin version
      description: Plugin version or build number. This can be found by running `/version plugin-name`
      placeholder: v3.1-SNAPSHOT-570b321
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Platform
      description: Server software - choose your proxy software if you have multiple servers
      options:
        - Spigot
        - BungeeCord
        - Velocity
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Relevance
      description: Check list for previous tickets
      options:
        - label: |
            I tried the [latest build](https://ci.codemc.io/job/Games647/job/FastLogin/) 
            (build refers to development builds not necessary a release version)
          required: true
        - label: |
            I checked for existing tickets -
            If there are, please vote them with a thumps reaction and not create new ones
          required: true
